### ISSUE TITLE
Clear layer tree on reconnects

### ISSUE THREAD

**Issue by joneschrisg** [mozilla/layerscope#4]
I tend to leave the UI open for a long time, across many reconnection cycles.  After reconnecting, it takes me a little bit to figure out whether the layer tree I'm seeing is the old one or a new one.  If the UI cleared the old layer tree on reconnecting, and/or ghosted out the old tree while disconnecting, the ergonomics would be improved for me.

**Comment by BorisChiou** [comment]
I filed a bug, https://bugzilla.mozilla.org/show_bug.cgi?id=1123534, to trace this issue. Thanks.
