### ISSUE TITLE
Optionally display layer tree in specified positions, blown out in 3d

### ISSUE THREAD

**Issue by joneschrisg** [mozilla/layerscope#5]
Seeing the flattened layer tree is 90% of the usefulness of the tool.  But there are some cases where the flattened view is hard to read.  It would be super cool if there were an option to position and transfor the layer tree according to the layer properties.  (Thinking here somewhat of the 3d DOM viewer in the FF dev tools.)

Since this would include a reimplementation of the layer compositor in JS+WebGL, it would also be a great resource for people ramping up on the layers code.

This would be a pretty big project so maybe something for an intern or GSoC.

**Comment by BorisChiou** [comment]
It's a good UX suggestion. I will discuss this with CJKu in our meeting.
