### ISSUE TITLE
Detect disconnects

### ISSUE THREAD

**Issue by cgjones** [mozilla/layerscope#6]
My workflow ends up with b2g restarting (or crashing) quite a bit.  It doesn't seem that the layerscope UI realizes that the layerscope server has gone down.  I don't know if this is because the UI hasn't installed an error handler, or the websocket itself isn't timing out (or whatever).

**Comment by BorisChiou** [comment]
Yes, it looks like a problem, and I should file a bug in bugzilla to trace this.

**Comment by BorisChiou** [comment]
Reference bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1123537

**Comment by BorisChiou** [comment]
https://github.com/mozilla/layerscope/commit/312717a8c38b80c48a9b52a2b53e08a5df16d845
