### ISSUE TITLE
Attempt to reconnect on a back-off timer (optionally)

### ISSUE THREAD

**Issue by joneschrisg** [mozilla/layerscope#7]
As I mentioned in #6, my workflow involves frequent restarts.  I imagine this is fairly common.  It would be great if layerscope would reconnect automatically after disconnects, with a back-off.  This along with #3, #4, and #6 would make for just about an optimal work environment for me.

The reconnect option should be optional because there are potential security problems.  But the UI should also remember my choice across reloads by storing the option persistently, a la #3.

**Comment by BorisChiou** [comment]
Actually, we are planning to integrate layerscope into WebIDE (https://bugzilla.mozilla.org/show_bug.cgi?id=946043), so the connection/reconnection could be much easier.
